# Default values for front-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: 'auth-api'
  namespace: 'smartclass'

replicas:
  count: 1
  revisionHistoryLimit: 0

image:
  version: main-c5916a6
  repository: 142373294051.dkr.ecr.us-east-1.amazonaws.com/auth
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  containerPort: 30001
